### ISSUE TITLE
Unknown voice track command: 0xac

### ISSUE THREAD

**Issue by netherbox** [digital-sound-antiques/mgsrc-js#1]
I'm trying to convert MSG tracks from https://www.msx.org/downloads/zanac-ex-opll-soundtrack

```
C:\ZNC-MGS> mgsrc-js ENDING.MGS
Unknown voice track command: 0xac
```

The same error message appears on https://msxplay.com/editor.html

**Comment by okaxaki** [comment]
Thank you. This is because #opll_tune was not supported. It has been solved at https://github.com/digital-sound-antiques/mgsrc-js/commit/04d963a6e5d4b5d7c337070c835cf78c058592f4
